name: Checks
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name : Run EC Validate (keyless)
      uses: ./
      with:
        image: ghcr.io/enterprise-contract/golden-container:latest@sha256:f0ee98623faef59b48d6d7a4537723de2e83f9c8b2f07708db17d00d5d0d4470 # latest
        identity: https:\/\/github\.com\/(slsa-framework\/slsa-github-generator|enterprise-contract\/golden-container)\/
        issuer: https://token.actions.githubusercontent.com

    #FIXME Commented out because the golden-image on quay.io is failing due to a violation in the image.
    # - name : Run EC Validate (Long_Lived)
    #   uses: ./
    #   with:
    #     image: quay.io/konflux-ci/ec-golden-image:latest
    #     key: ${{ vars.PUBLIC_KEY }}
    #     policy: github.com/enterprise-contract/config//slsa3
    #     extra-params: --ignore-rekor

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: ci
    if: needs.ci.outputs.status == 'success' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
    - name: Get Latest Version Tag and Increment
      run: |
        # Find the version tag and then increment new version with v prefix eg. v1.0.1 -> v1.0.2
        latestVTag=$(gh api -H 'Accept: application/vnd.github.v3+json' /repos/${{ github.repository }}/releases/latest -q '.tag_name')
        echo "newVersion=v$(echo ${latestVTag#v} | awk -F. '{$NF = $NF + 1;} 1' OFS=.)" >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Create New Version Release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
      with:
        name: ${{ env.newVersion }} Release
        body: ""
        tag_name: ${{ env.newVersion }}
        generate_release_notes: true
        draft: false
        prerelease: false
